### PR TITLE
GitHub Config documentation

### PR DESCRIPTION
**Pull request by yuhattor**
# GitHub Config documentation
In order to keep the history, I rebased and merged it.
Let's work on GitHub config docs here

- Conversation is moved from the PR https://github.com/InnerSourceCommons/managing-innersource-projects/pull/22
- Rebased and merged @JustinGOSSES's PR https://github.com/yuhattor/managing-inner-source-projects/pull/1 
- Working branch is moved from @yuhattor and @JustinGOSSES repository to InnerSourceCommons org's repo

## Summary
This pull request adds comprehensive documentation for InnerSource configuration on GitHub and GitLab, including essential settings and strategies for implementing InnerSource using these platforms. The most important changes include adding a new section to `tooling/innersource-tooling.md` with essential settings and strategies for implementing InnerSource using GitHub, and adding a new section to `tooling/github-strategy.md` with several subsections discussing various aspects of InnerSource collaboration.

Documentation improvements:

* <a href="diffhunk://#diff-b6435b0bba012b3c1afb3800c09a6b6649e2cf0cc10c21e06407a390ad4ceb28R1-R109">`tooling/github-configuration.md`</a>: Added comprehensive documentation for InnerSource configuration on GitHub, including guidance on layering source control management configurations, organization settings, and GitHub Enterprise Server settings. <a href="diffhunk://#diff-b6435b0bba012b3c1afb3800c09a6b6649e2cf0cc10c21e06407a390ad4ceb28R1-R109">[1]</a> <a href="diffhunk://#diff-b6435b0bba012b3c1afb3800c09a6b6649e2cf0cc10c21e06407a390ad4ceb28R1-R109">[2]</a>10)
* <a href="diffhunk://#diff-75dbbc7dbc758d5fbef277ff2ff0c23f8b35885c2abdba687b15a8a20cf47919R1-R34">`tooling/innersource-tooling.md`</a>: Added a new section with essential settings and strategies for implementing InnerSource using GitHub, including a table of contents with links to various subsections.
* <a href="diffhunk://#diff-41d6053e9d54af5fd243bee361e13e0390b1af3b7539e3dd7594e1a94fde30e7R1">`tooling/gitlab-configuration.md`</a>: Added a new section with essential settings and strategies for implementing InnerSource using GitLab.
* <a href="diffhunk://#diff-5bb2437d4fe7800538220fcbad35e7da04b44c134f2d10422a823b0bd07af440R1">`tooling/gitlab-strategy.md`</a>: Added a new section providing essential strategies for implementing InnerSource using GitLab.
* <a href="diffhunk://#diff-eba66d7be83b9dc1a4b22d5e8f99017f46ae937e820b56d01e070641d1a5c8edR1-R12">`tooling/authors.md`</a>: Added a new section that lists the authors and reviewers of the InnerSource documentation in chronological order.
* <a href="diffhunk://#diff-4097b1c2f7f4f5950bb76455a612de0b17d9c041e3a999283a291ceb9da46e39R1-R92">`tooling/github-strategy.md`</a>: Added a new section with several subsections discussing various aspects of InnerSource collaboration on GitHub.

### CODE REVIEW

**Comment by yuhattor** [comment]
@InnerSourceCommons/ispo-working-group-trusted-committers 

Once again, I am sorry 🙏  
I have merged a branch into mainline that has not been properly reviewed, so I have done the following.

- Reverted changes to mainline
- Rebased the commits including PR that @JustinGOSSES sent to my repository and the past changes in my forked branch and sent them as PR again.

**Comment by yuhattor** [comment]
As I mentioned in the past PR, I recently received some great insights from @jeffabailey
He gave me some input about his learning and I noticed that having clear objectives and defining success criteria is the key to success when it comes to the configuration. I want to incorporate those into this section as well.

**Comment by JustinGOSSES** [comment]
Great work @yuhattor !

**Review by yuhattor — COMMENTED** [review]
LGTM:)

**Review by rrrutledge — APPROVED** [review]

**Comment by rrrutledge** [comment]
Approved.  Should I merge as well?

**Comment by yuhattor** [comment]
Thank you! I think I can merge it

**Comment by spier** [comment]
Just confirming that this new documentation has been automatically published in the book as expected. See:
https://innersourcecommons.gitbook.io/managing-innersource-projects/innersource-tooling/github-strategy

**Comment by rrrutledge** [comment]
Wow 🤩

**Pull request merged**
