### PR TITLE
Update link to GitHub GQM graph page

### PR DESCRIPTION
**Pull request by rrrutledge**
* The graph links only work in GitHub.
* Because of that we want to have a link in the book back to GitHub.
* For some reason the link in the book points to the page in the book.
* Maybe GitBook is auto-replacing GitHub links to point to the corresponding GitBook page instead.
* Hopefully this Bitly link won't get so-replaced.

### CODE REVIEW

**Comment by spier** [comment]
An easier way to try this out would be to make the change in app.gitbook.com direct, I think they call it a change request, and then discard that again.

**Comment by spier** [comment]
Btw I think this is a shortcoming of the mermaidjs integration in gitbook. So my suspicion is that you won't be able to fix this.

**Comment by rrrutledge** [comment]
> make the change in app.gitbook.com direct, I think they call it a change request

OK check this out: https://app.gitbook.com/o/-MBYS3fpZ77O90pglFWi/s/-M3b_yGIW5Sz9pObaJm5/~/diff/~/changes/6/measuring/goals/use_gqm

**Comment by spier** [comment]
Ah. I had misunderstood this PR. Thought it was about changing the links that are embedded within the graph.

## About the issue

When gitbook sees a link that it already knows from the `SUMMARY.md`, then it will turn that link to an internal link within the gitbook instance. That's why you saw this translation:

From https://github.com/InnerSourceCommons/managing-inner-source-projects/blob/master/measuring/use_gqm.md
To https://innersourcecommons.gitbook.io/managing-innersource-projects/measuring/goals/use_gqm

So if you want to force a link back to the original markdown file, then your approach with a bitly link should work.

## As an aside:

I cannot see the bitly link in your change request in gitbook. For me it still looks like you are pointing to https://github.com/InnerSourceCommons/managing-innersource-projects/blob/main/measuring/use_gqm.md.

However that link does magically work right now, as we renamed `master` to `main` :)
Gitbook does not realize that those are the same links.

Will file a separate issue/PR to change all links embedded in the content from `master` to `main`.

**Comment by rrrutledge** [comment]
OK let’s just go with this Bitly approach, then?

**Comment by rrrutledge** [comment]
Why don't we get previews on pull request for what our GitBook looks like?

https://docs.gitbook.com/integrations/git-sync/github-pull-request-preview
https://app.gitbook.com/o/-MBYS3fpZ77O90pglFWi/s/-M3b_yGIW5Sz9pObaJm5/measuring/goals/use_gqm/~/gitsync/configure

**Review by JustinGOSSES — APPROVED** [review]
Looks good, lets try bitly

**Review by jeffabailey — APPROVED** [review]

**Pull request merged**
