### PR TITLE
[DON'T MERGE] Integrate Galician translation

### LINKED ISSUE #60: Translation to Galician
There is a project underway to translate this book to [Galician](https://en.wikipedia.org/wiki/Galician_language).

What makes this translation effort even more interesting, is that this translation work was contracted by a public administration, rather than run by a group of volunteers as the other translations of ISC material typically work.

The latest status of the translation work is available at:
https://github.com/psanxiao/managing-inner-source-projects-gl

Things to solve:
- how to merge this work into the upstream? (the repo above is current not a fork)
- how to release Galician, side-by-side with the English version in gitbook?
- how to handle future translations? (The English book will be undergoing major changes in the future. That means that the English and Galician version will be out of sync relatively quickly.)
- People that made the translation don’t have GitHub account. How to still acknowledge them and the authority that provided the fund properly?

### PR DESCRIPTION
**Pull request by spier**
Closes #60.

This working is still in a draft stage, as I am only using this branch to test out things in gitbook.

### CODE REVIEW

**Comment by spier** [comment]
> Neat! Is this basically the same idea and setup of what is done for the translation of the Patterns book?

It is similar but not quite the same. In both cases we use the collections/versioning feature of gitbook. The he difference in implementation is:

1) **patterns** - all languages merged into `main` branch. versions deployed from different folders.
2) **managing ISP** - languages kept in different branches

Approach (2) was the easiest to do a quick test deployment that the translators can review.
However long-term I like the approach (1) better as it allows you to see original and translation side-by-side, prevents long-lived branches, and allows us to acknowledge all contributors in the mainline.

Maybe a bit more information than you were looking for but doesn't hurt to document it :)

**Comment by rrrutledge** [comment]
This is great.

**Comment by spier** [comment]
FYI this PR won't actually be merged into `main`, as it would overwrite the English files of the book.
We only needed this PR to show the status of development and support the conversation.

I am therefore closing this PR, so that it does not get merged accidentally.

**Comment by spier** [comment]
The Galician translation of the book is published from the `translation-gl` branch itself.

This is now live at:
https://innersourcecommons.gitbook.io/managing-innersource-projects/v/gl/

**Comment by spier** [comment]
A couple of notes from the implementation of this:

- we opted to not show any country flags next to the languages. We could not find an emoticon of the Galician flag (first we used the Spanish flag but that would not be correct).
- added a Google Analytics ID to the project, to track traffic to both the English and Galician version
- made some styling changes to the layout of the published book. this could still be improved a lot.

Things left to do (for future PRs):

- @psanxiao and others will continue to send fixes to adapt the Galician version to the English original (some changes were made in the English version in the meantime that are not translated to Galician yet). Those fixes will be made towards the `translation-gl`
- Eventually we should restructure the repo, so that we can publish the translation from `main`. That allows us to attribute the contributors correctly and show them in the [overview of contributors](https://github.com/InnerSourceCommons/managing-innersource-projects/graphs/contributors). We could take some inspiration from the InnerSourcePatterns repo for this
- improve the layout/styling - e.g. create a logo for the book that can be used at the top right

**Pull request closed without merging**
